name: Bug Report
description: Report a bug in the Bengali Transliterator
title: '[Bug] '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of the tool are you using?
      placeholder: e.g., v1.0.0 or commit hash
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., 3.9.7
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Process file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actual behavior...
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Any error messages or output
      render: shell
      placeholder: Paste error output here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context about the problem
      placeholder: Additional context...
